// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using fussball.Data;

#nullable disable

namespace fussball.Migrations
{
    [DbContext(typeof(fussballContext))]
    [Migration("20231220144814_fkKampspiller1")]
    partial class fkKampspiller1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("fussball.Models.Kamp", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Dato")
                        .HasColumnType("datetime2");

                    b.Property<int>("ScoreLag1")
                        .HasColumnType("int");

                    b.Property<int>("ScoreLag2")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Kamp");
                });

            modelBuilder.Entity("fussball.Models.Kampspiller", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("KampId")
                        .HasColumnType("int");

                    b.Property<bool>("Lag1")
                        .HasColumnType("bit");

                    b.Property<int>("spillerId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("KampId")
                        .IsUnique();

                    b.ToTable("Kampspiller");
                });

            modelBuilder.Entity("fussball.Models.Spiller", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Etternavn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Fornavn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Spiller");
                });

            modelBuilder.Entity("fussball.Models.Kampspiller", b =>
                {
                    b.HasOne("fussball.Models.Kamp", null)
                        .WithOne("Kampspiller")
                        .HasForeignKey("fussball.Models.Kampspiller", "KampId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("fussball.Models.Kamp", b =>
                {
                    b.Navigation("Kampspiller")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
