// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using fussball.Data;

#nullable disable

namespace fussball.Migrations
{
    [DbContext(typeof(fussballContext))]
    [Migration("20231219145808_addedkamperclass")]
    partial class addedkamperclass
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("fussball.Models.Kamp", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Dato")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Kamp");
                });

            modelBuilder.Entity("fussball.Models.Spiller", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Etternavn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Fornavn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("KampId")
                        .HasColumnType("int");

                    b.Property<int?>("KampId1")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("KampId");

                    b.HasIndex("KampId1");

                    b.ToTable("Spiller");
                });

            modelBuilder.Entity("fussball.Models.Spiller", b =>
                {
                    b.HasOne("fussball.Models.Kamp", null)
                        .WithMany("Lag1")
                        .HasForeignKey("KampId");

                    b.HasOne("fussball.Models.Kamp", null)
                        .WithMany("Lag2")
                        .HasForeignKey("KampId1");
                });

            modelBuilder.Entity("fussball.Models.Kamp", b =>
                {
                    b.Navigation("Lag1");

                    b.Navigation("Lag2");
                });
#pragma warning restore 612, 618
        }
    }
}
